//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Repartidor", Namespace="http://schemas.datacontract.org/2004/07/SLWCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Repartidor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.UnidadEntrega))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.EstatusUnidad))]
    public partial class Repartidor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRepartidorService")]
    public interface IRepartidorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/Add", ReplyAction="http://tempuri.org/IRepartidorService/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReference1.Repartidor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.EstatusUnidad))]
        PL.ServiceReference1.Repartidor Add(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/Add", ReplyAction="http://tempuri.org/IRepartidorService/AddResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> AddAsync(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/Update", ReplyAction="http://tempuri.org/IRepartidorService/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReference1.Repartidor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.EstatusUnidad))]
        PL.ServiceReference1.Repartidor Update(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/Update", ReplyAction="http://tempuri.org/IRepartidorService/UpdateResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> UpdateAsync(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/Delete", ReplyAction="http://tempuri.org/IRepartidorService/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReference1.Repartidor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.EstatusUnidad))]
        PL.ServiceReference1.Repartidor Delete(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/Delete", ReplyAction="http://tempuri.org/IRepartidorService/DeleteResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> DeleteAsync(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/GetAll", ReplyAction="http://tempuri.org/IRepartidorService/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReference1.Repartidor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.EstatusUnidad))]
        PL.ServiceReference1.Repartidor GetAll(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/GetAll", ReplyAction="http://tempuri.org/IRepartidorService/GetAllResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> GetAllAsync(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/GetById", ReplyAction="http://tempuri.org/IRepartidorService/GetByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReference1.Repartidor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.UnidadEntrega))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.EstatusUnidad))]
        PL.ServiceReference1.Repartidor GetById(ML.Repartidor repartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepartidorService/GetById", ReplyAction="http://tempuri.org/IRepartidorService/GetByIdResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> GetByIdAsync(ML.Repartidor repartidor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepartidorServiceChannel : PL.ServiceReference1.IRepartidorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepartidorServiceClient : System.ServiceModel.ClientBase<PL.ServiceReference1.IRepartidorService>, PL.ServiceReference1.IRepartidorService {
        
        public RepartidorServiceClient() {
        }
        
        public RepartidorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepartidorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepartidorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepartidorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL.ServiceReference1.Repartidor Add(ML.Repartidor repartidor) {
            return base.Channel.Add(repartidor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> AddAsync(ML.Repartidor repartidor) {
            return base.Channel.AddAsync(repartidor);
        }
        
        public PL.ServiceReference1.Repartidor Update(ML.Repartidor repartidor) {
            return base.Channel.Update(repartidor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> UpdateAsync(ML.Repartidor repartidor) {
            return base.Channel.UpdateAsync(repartidor);
        }
        
        public PL.ServiceReference1.Repartidor Delete(ML.Repartidor repartidor) {
            return base.Channel.Delete(repartidor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> DeleteAsync(ML.Repartidor repartidor) {
            return base.Channel.DeleteAsync(repartidor);
        }
        
        public PL.ServiceReference1.Repartidor GetAll(ML.Repartidor repartidor) {
            return base.Channel.GetAll(repartidor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> GetAllAsync(ML.Repartidor repartidor) {
            return base.Channel.GetAllAsync(repartidor);
        }
        
        public PL.ServiceReference1.Repartidor GetById(ML.Repartidor repartidor) {
            return base.Channel.GetById(repartidor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference1.Repartidor> GetByIdAsync(ML.Repartidor repartidor) {
            return base.Channel.GetByIdAsync(repartidor);
        }
    }
}
